//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public int sno { get; set; }
        public Nullable<decimal> Account_No { get; set; }
        public string Mode { get; set; }
        public string Dollars { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> Interest_rate { get; set; }
        public string Maturity_date { get; set; }
        public Nullable<decimal> Maturity_Amount { get; set; }
        public string Start_Date { get; set; }
    }
}
